### ISSUE TITLE
Handle situations when python3 is not in /usr/bin/python3

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#15]
On our HPC, I need to load a module to have python3

**Comment by aswinnarayanan** [comment]
If you load a module python or virtualenv, and then run build.sh, does it still use the wrong python?

**Comment by civier** [comment]
No. Then it's fine.
I think you simply need to show an error message if python3 is not available in the path

**Comment by stebo85** [comment]
moved to #13
