### ISSUE TITLE
Install on HPC

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#16]
In HPC, one doesn't have all the desktop related files, and if I don't specify directories, build.sh fails.
Need to add an option to install without the desktop stuff/menus

**Comment by stebo85** [comment]
@civier - you don't need to run build.sh on an HPC. Only install and than download containers 

Could be made more explicit in the documentation @aswinnarayanan?

**Comment by aswinnarayanan** [comment]
You don't need to run install.sh on HPC. Just build.sh ( --lxde mode will stop any menu errors)

Will  just create a proper containers flag to fix this properly

**Comment by civier** [comment]
Even with the --cli option, I still get an error on /etc/xdg/menus/lxde-applications.menu

Traceback (most recent call last):
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ocivier/git/neurodesk/neurodesk/__main__.py", line 2, in <module>
    neurodesk.main()
  File "/home/ocivier/git/neurodesk/neurodesk/neurodesk.py", line 138, in main
    appmenu.resolve(strict=True)
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/pathlib.py", line 1151, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/pathlib.py", line 355, in resolve
    return _resolve(base, str(path)) or sep
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/pathlib.py", line 339, in _resolve
    target = accessor.readlink(newpath)
  File "/apps/skylake/software/compiler/gcc/6.4.0/python/3.7.4/lib/python3.7/pathlib.py", line 437, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/xdg/menus/lxde-applications.menu'

**Comment by aswinnarayanan** [comment]
https://github.com/NeuroDesk/neurodesk/commit/fa3239e2ef7b66be7120708ce9bbd62caee94c68
Does this fix the error?

**Comment by civier** [comment]
Some containers.sh issues:
1) Need to print an error if Singularity is not in path (otherwise, there are errors all thorugh).
2) It searches for ts_binaryFinder.sh in my home directory (i.e. print "FATAL:   stat /home/ocivier/ts_binaryFinder.sh: no such file or directory")
3) Still prints "Container successfully installed" after each container install, which is a problem I believe

**Comment by civier** [comment]
I manually copied ts_binaryFinder.sh to my home directory, and now it works (but please fix for the future).
Now I get another error, though:
./run_transparent_singularity.sh: line 156: commands.txt: No such file or directory
See below full log for when containers.sh tries to install tgvqsm

-------------------------------------
IMPORTANT: you need to set your system specific mount points in your .bashrc!: e.g. export SINGULARITY_BINDPATH="/opt,/data"
-------------------------------------
containerName: tgvqsm
containerVersion: 1.0.0
containerDate: 20200929
containerEnding: sif
trying if tgvqsm_1.0.0_20200929.sif exists in the cache
tgvqsm_1.0.0_20200929.sif exists in the cache
checking for singularity ...
deploying in /fred/oz120/oren/neurodesk/local/containers/tgvqsm_1.0.0_20200929
checking if container needs to be downloaded
container downloaded already. Remove to re-download!
making container executable
checking which executables exist inside container
create singularity executable for each regular executable in commands.txt
./run_transparent_singularity.sh: line 156: commands.txt: No such file or directory
creating activate script that runs deactivate first in case it is already there
deactivate script
create module files one directory up
Container successfully installed

**Comment by aswinnarayanan** [comment]
2. Could you post your config.ini?
3. It says successful container install when the installation failed?

**Comment by civier** [comment]
Fixed the commands.txt issue in https://github.com/NeuroDesk/neurodesk/commit/0b80cb05f48191f758e93e12a16f1c750c74cfde
Hope it's ok for me to edit. If not, revert.

**Comment by aswinnarayanan** [comment]
@civier, saw your changes and comments

My guess is `pwd -P` in transparent_singularity is causing the issues. 
If that's the case, I think we should switch to this snippet to find and use the script directory. 

_script="$(readlink -f ${BASH_SOURCE[0]})" ## who am i? ##
_base="$(dirname $_script)" ## Delete last component from $_script ##

I'll give it a try and see if it resolves things

**Comment by aswinnarayanan** [comment]
@civier, feel free to re-open if more issues present. Closing
