### ISSUE TITLE
Module use

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#17]
Add to readme instructions how to enable nuerodesk modules on startup.
According to what Steffen told me: 
**The users simply have to run module use PATH_TO_NEUORDESK_MODULES – and this could be added to their .bashrc or they run it manually everytime.**

BTW, do you want me to update neurodesk's readme and code directly? I'm not sure.

**Comment by aswinnarayanan** [comment]
Please feel free to make any updates/changes

**Comment by stebo85** [comment]
any updates on this one @civier ?
