### ISSUE TITLE
Downloading Singularity container is very slow and does not terminate 

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#21]
I was trying to download the updated fsl 6.0.4 container to OzStar (Swinburne HPC) at 11:30pm 9th of Nov. The download was extremely slow (said it will take approx. a hour) and terminated prematurely (see log below).
Do you know why the NECTAR object storage is so slow and unreliable? Is it common? I didn't get any notices on issues with NECTAR, but let me know if it was something temporary.

Another related issue -- when the download is terminated prematurely (as in the case below), the partial .sif file stays on the file system. If I try to install the container again, it assumes the .sif file was downloaded appropriately, but the installer obviously fails when trying to interact with the container. You should catch it if the download was not complete, and delete the partial file (or the whole directory, if necessary for proper operation).

```
[ocivier@farnarkle2 neurodesk]$  /dagg/public/neuro/neurodesk/local/fetch_containers.sh fsl 6.0.4 20201029 |& tee all_execs-fsl_6.0.4_log.txt
/dagg/public/neuro/neurodesk/local/config.ini
CONTAINER_PATH: /dagg/public/neuro/neurodesk/local/containers
MODS_PATH: /dagg/public/neuro/neurodesk/local/containers/modules
trying to module use  /dagg/public/neuro/neurodesk/local/containers/modules
Lmod has detected the following error: Unable to find: "fsl/6.0.4".



-------------------------------------
installing container fsl_6.0.4_20201029.sif
-------------------------------------
-------------------------------------
IMPORTANT: you need to set your system specific mount points in your .bashrc!: e.g. export SINGULARITY_BINDPATH="/opt,/data"
-------------------------------------
containerName: fsl
containerVersion: 6.0.4
containerDate: 20201029
containerEnding: sif
trying if fsl_6.0.4_20201029.sif exists in the cache
fsl_6.0.4_20201029.sif exists in the cache
checking for singularity ...
deploying in /dagg/public/neuro/neurodesk/local/containers/fsl_6.0.4_20201029
checking if container needs to be downloaded
pulling image now ... this will take some time!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 6684M    0 21.4M    0     0  33774      0 57:39:05  0:11:05 57:28:00 34436
curl: (18) transfer closed with 6987177984 bytes remaining to read
```

**Comment by civier** [comment]
UPDATE:
Tried a few minutes later, and it downloaded the container at no time.
Do you see such severe performance fluctuations frequently? Do you think it is at the NECTAR's or the Swinburne's side?

**Comment by stebo85** [comment]
Dear @civier ,

We haven't seen such an issue before and I think it might be a network problem on your side. Detecting a corrupted sif file should already work - it should have gave you an error the second time you tried that asked you to delete the file? Did this not come up?

Cheers
Steffen

**Comment by stebo85** [comment]
I now added more error handling that detects if a container did not start and it offers to delete it 
commit e3be524
