### ISSUE TITLE
make screen resolution dynamic based on VNC window size

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk#24]

**Comment by aswinnarayanan** [comment]
This function is partly available on  [neuromachine](https://github.com/NeuroDesk/neuromachine)
- Neuromachine RDP Desktop supports this function
- Neuromachine VNC Desktop via web browser currently only supports auto-scaling (i.e. zooming) and resolution can be changed manually via LXDE monitor settings (needs documentation)
- TigerVNC client supports auto-resolution.

Looks like VNM auto-resolution is a current limitation on the Guacamole VNC client. Updates here: [GUACAMOLE-1196: Add auto resize to VNC sessions](https://issues.apache.org/jira/browse/GUACAMOLE-1196)
