### ISSUE TITLE
build a github pages website for the project 

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk#28]

**Comment by i-am-mel-dev** [comment]
Found https://github.com/radekosmulski/personal-site and want to test it because it seems like a super simple thing based on this https://andybrewer.github.io/mvp/ and looks cool a well, what do you think?

**Comment by stebo85** [comment]
Cool - this looks great :)

**Comment by aswinnarayanan** [comment]
Done. https://github.com/NeuroDesk/neurodesk.github.io
