### ISSUE TITLE
reorganise documentation into github-pages

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk#30]

**Comment by meganEJcampbell** [comment]
Keen to try to help if I can (during 2021 brainhack). Does anyone have notes that I can compile into documentation?
 Is there a good how-to someone can suggest for creating a GitHub Wiki perhaps?

**Comment by aswinnarayanan** [comment]
Hi @meganEJcampbell. There is a wiki here [https://github.com/NeuroDesk/vnm/wiki]()
That currently hosts all the advanced documentation that isn't already present on either the neurodesk or vnm README

**Comment by meganEJcampbell** [comment]
Ahh I was looking here: https://github.com/NeuroDesk/neurodesk/wiki 
So what's needed to contribute to this issue #30?

**Comment by aswinnarayanan** [comment]
This issue is referring building documentation via [readthedocs.org](https://github.com/readthedocs/readthedocs.org)
I'll have an account linked up via the quick-start. @meganEJcampbell, would you keen to help contribute to it?

**Comment by meganEJcampbell** [comment]
On second thoughts, I'm such a newbie that my trying to contribute to this will become work for others trying to help me learn how to contribute!

**Comment by stebo85** [comment]
Dear @meganEJcampbell - it's super valuable to have you input - I also don't have any idea about readthedocs and how to document things nicely. So anything helps :)

**Comment by aswinnarayanan** [comment]
Hi @meganEJcampbell, your contribution would be incredibly valuable. The project is currently lacking a lot in documentation. 

I suggest we use github-pages to handle the documentation.

readthedocs looks quite powerful, especially when it comes to versioning and tagging, but it uses reStructuredText.

github-pages uses markdown, it'll be much easier to edit and preview, while being more organised than the wiki

**Comment by aswinnarayanan** [comment]
There's a new github pages site for central documentation at https://github.com/NeuroDesk/neurodesk.github.io

All pages can be via the browser and markdown, there's a short guide on the front page regarding Markdown
It uses [index.md](https://github.com/NeuroDesk/neurodesk.github.io/blob/main/index.md) as the homepage and further pages can organised into [docs/](https://github.com/NeuroDesk/neurodesk.github.io/tree/main/docs) with links on [index.md](https://github.com/NeuroDesk/neurodesk.github.io/blob/main/index.md)

If anyone has any questions, please feel free to create new issues under [neurodesk.github.io/issues](https://github.com/NeuroDesk/neurodesk.github.io/issues)

Good starting place could be to reorganise the [wiki](https://github.com/NeuroDesk/vnm/wiki) onto [neurodesk.github.io](https://github.com/NeuroDesk/neurodesk.github.io)

**Comment by stebo85** [comment]
Wow, this looks awesome already!!!!!

**Comment by stebo85** [comment]
@meganEJcampbell and @aswinnarayanan - great work on this :) I like the new landing point to the project a lot!

**Comment by meganEJcampbell** [comment]
Brilliant so I'll focus on reorganising what's in the wiki into the content for your github-page. I'll try my best but fair warning this is my first attempt at such a thing! Also it will have to be next week at the earliest.

**Comment by stebo85** [comment]
sounds great :) Thank you!

**Comment by aswinnarayanan** [comment]
Issue can be closed. Thanks @meganEJcampbell
