### ISSUE TITLE
test if neurodesk containers runs on free tier of oracle, amazon, google, azure

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk#31]

**Comment by stebo85** [comment]
tested for oracle cloud - works :)

**Comment by henry-burgess** [comment]
Hey @stebo85, I came across this project though QBI, so I decided to try spinning it up for free on Azure: https://henryjburg.medium.com/neurodesk-running-on-azure-3e38c590a152

Seems to work fine 😅

I'm planning to try it out on Google and AWS later too.

**Comment by stebo85** [comment]
That's wonderful to hear @henry-burgess. Thank you so much for testing this and reporting back and for the blogpost describing it :)

**Comment by stebo85** [comment]
closing for now as the new CVMFS implementation makes it pretty much run on any free tier :)
