### ISSUE TITLE
Freesurfer container looks for license file in wrong place

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#45]
The freesurfer container seems to set FS_LICENSE to /home/runner/license.txt at container initialisation
Even if I try to set it explicitly before calling the container, it is still being overwritten
FS_LICENSE should be unset, so freesurfer will look for the license file in the home directory of the user (the default)

**Comment by stebo85** [comment]
Dear Oren,

Thank you for flagging this. I made an attempt at fixing this and containers are currently rebuilding :)

Cheers
Steffen

**Comment by stebo85** [comment]
Dear @civier, can you confirm if the updated containers work for you now?

**Comment by stebo85** [comment]
closing. I tested it myself and it's working now (also updated documentation of FreeSurfer)
