### ISSUE TITLE
Accessing data files that come with software packages using external applications

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#46]
Some software packages include not only executables, but also data files. Some users might wish to use these data files using external tools. An example might be using FSL MNI templates using MRtrix. I wonder if we should seek some solutions to make files from within the container available externally? 
The user can always run the container interactively and copy the file to the home directory, so the first thing we need to do I think is adding a command to open a package container interactively (it exists through the menu in VNM, but we should also add a command-line option for those working on HPC, for example).
However, we can do something even smarter. For example, let the user access a file within the container by calling something like $(extract_file package_name path_within_container). This will copy the file at path_within_container to a temporary location outside the container, and then return the temporary location as a string. This way the user won't need to keep copies of files within the container, which will contribute to better integrity (especially when upgrading package versions, etc.) 
Any thoughts?

**Comment by stebo85** [comment]
I am currently working on making all our containers available on CVMFS in an unpacked format - then users can directly use atlases from within the files.

**Comment by civier** [comment]
That's a nice approach, but would not cover all scenarios. For example, the computing nodes on our HPC do not have internet access, so we'll need to have the files locally (unless there is an easy way for HPCs to mirror everything?)

**Comment by stebo85** [comment]
yes, cvmfs allows to download the software repository and make it available to all nodes if compute nodes don't have internet access

**Comment by civier** [comment]
How often does it update? Can you send me some info on this option so I'll check if the folks at our HPC would support it?

**Comment by stebo85** [comment]
it can update as often as one sets it e.g. in a cron-job:
https://cvmfs.readthedocs.io/en/stable/cpt-hpc.html#downloading-complete-snapshots-of-cernvm-fs-repositories
