### ISSUE TITLE
Why not loading all modules by default?

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#48]
Why not loading all downloaded modules by default, so users won't even need to do ml. Just to make things simpler and more intuitive.
There is always the chance that two packages will have overlapping commands, but then the user can unload the one not needed.
Did you check if there are even any conflicts that we need to worry about? On our HPC I load for users all NeuroDesk modules by default, and no issue.

**Comment by aswinnarayanan** [comment]
Is this for Neurodesk container only mode?
Or VNM as well?

**Comment by civier** [comment]
Whichever. I guess that HPCs don't do it by default because there will be clash between dynamic libraries required by different packages, but in our case it's a non-issue.

**Comment by stebo85** [comment]
Dear Oren,

There are a couple of contianers with overlapping binary names (e.g. FreeSurfer, QSMxT, mrtrix, fsl, fmriprep), so loading all of them would lead to problems. 

Best
Steffen

**Comment by stebo85** [comment]
closing, because it would lead to a lot of problems with overlapping binary names.
