### ISSUE TITLE
Sometimes when choosing a GUI application from the menu for the first time, it won't open

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#49]
Sometimes when choosing a GUI application from the menu for the first time, the respective package IS downloaded, but the GUI application DOES NOT open. Unfortunately, the terminal with the log closes as well, so it's difficult for me to debug it. Is there a global log for NeuroDesk where I can go back and check such things? If not, will be a good idea to have one in future versions.
Notice that when I click on the same GUI application again, it DOES open properly (I tested it with the latest versions of FSL and MRtrix).
I'm using VNM version 20210130

**Comment by stebo85** [comment]
closed due to inactivity and couldn't reproduce the problem.
