### ISSUE TITLE
Seg fault when closing fsleyes

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#50]
When running fsleyes from a terminal within VNM that is running on a NECTR instance, I get this error printed when I close the fsleyes window:
/vnm/containers/fsl_6.0.4_20210105/fsleyes: line 3:  9453 Segmentation fault      singularity exec --pwd $PWD /vnm/containers/fsl_6.0.4_20210105/fsl_6.0.4_20210105.simg fsleyes $@

VNM version is 20210130. 

Need to check if replicates on newest version of VNM

**Comment by stebo85** [comment]
This looks like a bug in FSLeyes that we cannot do much about. Does it happen for other fsl container versions as well? It shouldn't depend on the VNM version.
