### ISSUE TITLE
Changing VNM screen size should be in menu

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#52]
For people that only use the GUI, this might the only time when they need to run something in the terminal, and we don't want it. Also, it is cumbersome to run a command everytime you want to change screen size.

**Comment by stebo85** [comment]
Dear @civier, this should be doable via a script in the menu of VNM, you should try to add it and propose a pull request: I would start here:
https://github.com/NeuroDesk/neurodesk/blob/master/vnm/Dockerfile

**Comment by stebo85** [comment]
related to #24 and should be discussed there.
