### ISSUE TITLE
ONLY FIX IF PROBLEM REPLICATES -- Problem after resizing

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#58]
After resizing the VNM window with "curl localhost:6079/resize" and reconnecting, trying to re-launch "mrtrix3 3.0.2" from the menu (it was already downloaded and launched before the resize), pops up the following error:
![MRTRIX_Error](https://user-images.githubusercontent.com/8280611/117231321-5b7ed980-ae62-11eb-8f4e-44540f63a3b1.jpg)
In addition, when trying to launch "mrviewGUI 3.0.2", nothing happens.
Any clue what causes for the problem?
(notice that when opening a terminal, running "ml mrtrix3" and then "mrview", it works fine)

Happened on Dave White's VNM@Cloud

**Comment by stebo85** [comment]
yes, the whole screen resizing implementation is very experimental and unlikely to work reliably. It would be good to find a better alternative there. Please feel free to submit constructive ideas how to improve on this.

**Comment by stebo85** [comment]
should be discused in #24
