### ISSUE TITLE
Add the "screen" command to base VNM image

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#59]
Right now, resizing the screen using the curl command will terminate all running applications. Terminal applications can survive if being ran within a "screen" session, but "screen" is not currently installed.
screen should be added then to the base image.

**Comment by stebo85** [comment]
yes, screen is a useful edition. Feel free to submit a pull request adding it to the base image

**Comment by aswinnarayanan** [comment]
Thanks @stebo85. Resolved here https://github.com/NeuroDesk/vnm/commit/29f55bfafa3253523a06fe60491edb6d4c66a3b3
