### ISSUE TITLE
add DICOM to BIDS converter (possibly dcm2niibatch or dcm2bids) + dicom2niix

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesk#6]

**Comment by stebo85** [comment]
done - I added bidstools container container dcm2niix and bidscoin

**Comment by civier** [comment]
Will be good to mention somewhere what the bidstools container contains. Can we add one sentence descriptions to one of the lists that are linked to from the GitHub readme?

**Comment by stebo85** [comment]
I documented it in the readme of the container: 
https://github.com/NeuroDesk/caid/tree/master/recipes/bidstools

where else would be helpful?
