### ISSUE TITLE
Problem with WSL2 install using RDP

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesk#60]
I've followed all instructions on the WSL2 install (singularity, Lmod, xdrp, etc all working) - up until the final step where I open windows RDC and have localhost:3390 as the computer.
The xrdp login promts 'session {Xorg}, username {blank} password {blank} ' 
I click OK and get a login error. 
![image](https://user-images.githubusercontent.com/31721414/117917867-54a60a00-b32d-11eb-9c2c-14e0e52d32bc.png)

**Comment by aswinnarayanan** [comment]
Hi @thomshaw92. If you fill in the WSL username and password in the xrdp login, do you get the same error?

**Comment by stebo85** [comment]
Dear @thomshaw92 - can you test if this worked for you, so we can close this issue?

**Comment by thomshaw92** [comment]
Yep that worked.
