### ISSUE TITLE
Wrong text under the NeuroDesk installer heading

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#79]
Under the "NeuroDesk installer" heading on NeuroDesk webpage, it says:
"A flexible, scalable, and easy to use data analysis environment for reproducible neuroimaging. Virtual Neuro Machine (or VNM) pre-installs Neurodesk in an Ubuntu docker container providing simple access to the powerful capabilities of Neurodesk."

This is a description of VNM, so I think it is misplaced.

**Comment by aswinnarayanan** [comment]
https://github.com/NeuroDesk/neurodesk.github.io/commit/3621f16abba21d249559409abd151fe60ae9aad0
