### ISSUE TITLE
A recent freesurfer container might be corrupted

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#91]
Freesurfer 7.1.1 20210105 which was in the menu of a previous VNM version may be defective, as we get errors when either running or unpacking it.
I can send the full error message if necessary.

**Comment by stebo85** [comment]
Dear @civier ,

Freesurfer 7.1.1 20210105 is depcrecated and the working version is freesurfer_7.1.1_20210225

Please update your VNM container to the current version.

**Comment by civier** [comment]
OK. Is there a way to change it in an active container, or do I need to stop/start the container to make changes to the menu? Or is it that the only way to upgrade the menu is to move to a new VNM version, as you suggest? (that would be costly, as people are currently using NECTAR instances with the old one)
BTW, is it documented somewhere that 20210105 is deprecated? or do we have a readme for every specific version of VNM? We will discuss documentation in the next AEDAPT meeting, so I can bring it up then.

**Comment by aswinnarayanan** [comment]
Hi @civier. 

On a running vnm container, the menu can be updated using the neurodesk update commands found here [here](https://github.com/NeuroDesk/neurodesk#to-update). The neurodesk directory is at /neurodesk on vnm.

But, I'd strongly advice that they shutdown the current vnm, pull the latest version and run that instead to fix it.

**Comment by civier** [comment]
Thanks @aswinnarayanan

May I ask why does neurocontainers even have multiple versions of a specific container, like FreeSurfer 7.1.1?
https://github.com/NeuroDesk/neurocontainers/pkgs/container/caid%2Ffreesurfer_7.1.1
Are those versions of freesurfer 7.1.1 with different patches? Or is it that all the old versions are deprecated and were replaced by new ones due to bugs, etc.?

"I think neurocontainers would be the best place to track deprecated builds."
Yes. I agree. How do I add description to specific tags? Can it be done via the GitHub website?

"Neuromachine now updates to the latest version of neurodesk on startup, so it might fix the issue. We plan to replace vnm with neuromachine, so its recommended we address the issue there."
Can you please make it optional? One feature of VNM is to have a 100% reproducible environment, and having exactly the same version of Neurodesk is also part of it.

**Comment by aswinnarayanan** [comment]
> May I ask why does neurocontainers even have multiple versions of a specific container, like FreeSurfer 7.1.1?
> https://github.com/NeuroDesk/neurocontainers/pkgs/container/caid%2Ffreesurfer_7.1.1
> Are those versions of freesurfer 7.1.1 with different patches? Or is it that all the old versions are deprecated and were replaced by new ones due to bugs, etc.?

The tags are the date that the container image was built. Its probably due to some changes in the container recipe. You would have to investigate the repo and commit of the recipe file that generated the image, the commit information is tagged as a label [here](https://github.com/NeuroDesk/neurocontainers/blob/d3395fc97672319f9f953990359891cc19865bcf/.github/workflows/build-docker.sh#L21)

> "I think neurocontainers would be the best place to track deprecated builds."
> Yes. I agree. How do I add description to specific tags? Can it be done via the GitHub website?

Not sure, I haven't looked into a solution for this.

> "Neuromachine now updates to the latest version of neurodesk on startup, so it might fix the issue. We plan to replace vnm with neuromachine, so its recommended we address the issue there."
> Can you please make it optional? One feature of VNM/NeuroMachine is to have a 100% reproducible environment, and having exactly the same version of Neurodesk is also part of it.

I'll have a look into this

**Comment by civier** [comment]
@stebo85 Do you know why the freesurfer 7.1.1 container was re-built so many times. Were there any issues with it?
@DavidjWhite33 wants to know.

**Comment by stebo85** [comment]
@civier, yes there were a couple of issues with the freesurfer container. Please have a look at the git history of the build script where it is documented.
