### ISSUE TITLE
Giving Dave permission to edit neurocontainers

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#93]
Hi @aswinnarayanan and @stebo85 

Could you please grant Dave (@DavidjWhite33) permission to edit neurocontainers (https://github.com/NeuroDesk/neurocontainers)
He starts experimenting with adding containers to NeuroDesk, and trying to follow the instructions you provide here:
https://github.com/NeuroDesk/neurocontainers#adding-new-recipes

Thanks ahead,
Oren

**Comment by aswinnarayanan** [comment]
Hi @civier. You should be able to add @DavidjWhite33

**Comment by stebo85** [comment]
Dear @civier 

I am not sure why you were not able to add @DavidjWhite33 yourself to the repo. I added him now.

Cheers
Steffen

**Comment by civier** [comment]
Thanks Steffen and Aswin.
I thought I do not have permission to add extra developers. Sorry about
that.

Best,
Oren
